/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "tertiary-container": "#007030",
        "secondary-fixed": "#acedff",
        "on-tertiary-container": "#63f889",
        "tertiary-fixed": "#6bff8f",
        "on-secondary-fixed": "#001f26",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#002109",
        "primary": "#3525cd",
        "on-secondary-container": "#006172",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed-variant": "#005321",
        "tertiary": "#005523",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#464555",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
        "outline-variant": "#c7c4d8",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#4d44e3",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "inverse-surface": "#213145",
        "secondary": "#00687a",
        "error-container": "#ffdad6",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#4ae176",
        "on-error": "#ffffff",
        "secondary-container": "#57dffe",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-primary-fixed": "#0f0069",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#dad7ff",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#004e5c",
        "outline": "#777587",
        "inverse-primary": "#c3c0ff",
        "primary-container": "#4f46e5",
        "background": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "xl": "32px",
        "base": "4px",
        "sm": "8px",
        "md": "16px",
        "gutter": "16px",
        "lg": "24px",
        "container-margin": "20px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "title-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"]
      },
      fontSize: {
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
